name: test
pool: Default
steps:
- script: mkdir c:\test2
    
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"