name: test
pool: Default
trigger: none
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $install_folder = 'C:\Program Files\Java'
      $filename = Get-ChildItem -Path C:\IIQSoftware\Java\*.zip | Sort-Object -Property LastWriteTime -Descending | Select-Object -First 1
      Expand-Archive -Path $filename -DestinationPath $install_folder -Force
      $java_folder = Get-ChildItem -Path $install_folder -Directory | Sort-Object -Property LastWriteTime -Descending | Select-Object -First 1
      $java_home=$install_folder +"\"+ $java_folder
      Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name JAVA_HOME -Value $java_home
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $install_folder = 'C:\Program Files\Apache Software Foundation'
      $oldTomcatFolderName="Tomcat 9.0_old"
      $newTomcatFolderName="Tomcat 9.0"
      $filename = Get-ChildItem -Path C:\IIQSoftware\Apache-Tomcat\*.zip | Sort-Object -Property LastWriteTime -Descending | Select-Object -First 1
      Rename-Item -Path "C:\Program Files\Apache Software Foundation\Tomcat 9.0" -NewName $oldTomcatFolderName
      Expand-Archive -Path $filename -DestinationPath $install_folder -Force
      $unzippedTomcatName = Get-ChildItem -Path $install_folder -Directory | Sort-Object -Property LastWriteTime -Descending | Select-Object -First 1
      Rename-Item -Path $install_folder\$unzippedTomcatName -NewName $newTomcatFolderName
      Move-Item -Path $install_folder\$oldTomcatFolderName\webapps\identityiq -Destination $install_folder\$newTomcatFolderName\webapps
      Remove-Item -Path $install_folder\$oldTomcatFolderName -Recurse
- script: |
    cd "C:\Program Files\Apache Software Foundation\Tomcat 9.0\bin"
    tomcat9 //DS//tomcat9
    service.bat install tomcat9
    set CATALINA_BASE="C:\Program Files\Apache Software Foundation\apache-tomcat-9.0.50"
    set CATALINA_HOME="C:\Program Files\Apache Software Foundation\apache-tomcat-9.0.50"
    set ENDORSED_PROP=ignore.endorsed.dirs
    set JvmMs=128
    set JvmMx=1024
    tomcat9 //US//tomcat9 --JvmOptions -Dcatalina.home=%CATALINA_HOME%;-Dcatalina.base=%CATALINA_BASE%;-D%ENDORSED_PROP%=%CATALINA_HOME%\endorsed;-Djava.io.tmpdir=%CATALINA_BASE%\temp;-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager;-Djava.util.logging.config.file=%CATALINA_BASE%\conf\logging.properties;-XX:ParallelGCThreads=2;-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT --JvmMs=%JvmMS% --JvmMx=%JvmMX% --Startup=auto


