name: test
pool: DEV
trigger: none
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $arrService = Get-Service -Name tomcat9
      if ($arrService.Status -eq 'Running'){Stop-Service tomcat9}
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $install_folder = 'C:\Program Files\Java'
      $filename = Get-ChildItem -Path C:\IIQSoftware\Java\*.zip | Sort-Object -Property LastWriteTime -Descending | Select-Object -First 1
      Expand-Archive -Path $filename -DestinationPath $install_folder -Force
      $java_folder = Get-ChildItem -Path $install_folder -Directory | Sort-Object -Property LastWriteTime -Descending | Select-Object -First 1
      $java_home=$install_folder +"\"+ $java_folder
      $elements = $Env:Path.Split(";")
      foreach ($e in $elements){
        if($e -ne $toRemove){
          $newPath += "$e;"
        }
      }
      $newPath += "%JAVA_HOME%\bin"
      Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name Path -Value $newPath
      Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name JAVA_HOME -Value $java_home
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $install_folder = 'C:\Program Files\Apache Software Foundation'
      $oldTomcatFolderName="Tomcat 9.0_old"
      $newTomcatFolderName="Tomcat 9.0"
      $tomcatPath="C:\Program Files\Apache Software Foundation\Tomcat 9.0"
      $filename = Get-ChildItem -Path C:\IIQSoftware\Apache-Tomcat\*.zip | Sort-Object -Property LastWriteTime -Descending | Select-Object -First 1
      if (Test-Path -Path $tomcatPath) {
        Rename-Item -Path $tomcatPath -NewName $oldTomcatFolderName
      }
      Expand-Archive -Path $filename -DestinationPath $install_folder -Force
      $unzippedTomcatName = Get-ChildItem -Path $install_folder -Directory | Sort-Object -Property LastWriteTime -Descending | Select-Object -First 1
      Rename-Item -Path $install_folder\$unzippedTomcatName -NewName $newTomcatFolderName
      if (Test-Path -Path $install_folder\$oldTomcatFolderName\webapps\identityiq) {
        Move-Item -Path $install_folder\$oldTomcatFolderName\webapps\identityiq -Destination $install_folder\$newTomcatFolderName\webapps
      }
      if (Test-Path -Path $install_folder\$oldTomcatFolderName) {
        Remove-Item -Path $install_folder\$oldTomcatFolderName -Recurse
      }
- script: |
    cd %CATALINA_HOME%\bin
    tomcat9 //DS//tomcat9
    service.bat install tomcat9
- script: |
    cd %CATALINA_HOME%\bin
    tomcat9 //US//tomcat9 --JvmOptions "-Dcatalina.home=%CATALINA_HOME%;-Dcatalina.base=%CATALINA_HOME%;-Dignore.endorsed.dirs=%CATALINA_HOME%\endorsed;-Djava.io.tmpdir=%CATALINA_HOME%\temp;-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager;-Djava.util.logging.config.file=%CATALINA_HOME%\conf\logging.properties;-XX:ParallelGCThreads=2;-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT" --JvmMs=1024 --JvmMx=4096 --Startup=auto
    sc config Tomcat9 obj=LocalSystem
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $arrService = Get-Service -Name tomcat9
      if ($arrService.Status -eq 'Stopped'){Start-Service tomcat9}